### ISSUE TITLE
'Mesh' object has no attribute 'uv_textures'

### ISSUE THREAD

**Issue by olsonpm** [stante/blendm3#13]
This error occurred when attempting to import [this model](https://github.com/stante/blendm3/files/4039057/Chooser_00.zip)

Blender version 2.81a

```
Traceback (most recent call last):
  File "C:\Users\phil\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\import_shape_m3.py", line 1040, in execute
    self.search_textures)
  File "C:\Users\phil\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\import_shape_m3.py", line 988, in load
    mesh.uv_textures.new()
AttributeError: 'Mesh' object has no attribute 'uv_textures'

location: <unknown location>:-1
```

Looks like an api incompatibility as [the new python api doesn't support uv_textures](https://docs.blender.org/api/master/change_log.html#id114)

> Removed
> ...
> uv_textures

I'm a developer and familiar with python but have never used blender before so I don't feel comfortable taking on a PR atm.  I'll use a compatible version of blender in the meantime.

Thanks so much for this plugin

**Comment by KekLuck** [comment]
Did you find a solution for this? Which Blender Version is viable? ATM no one works for me ^^

**Comment by olsonpm** [comment]
after chatting in the sc2 map making discord it was recommended to use a different plugin.  I believe this one

https://github.com/Talv/m3addon

but can't verify since I'm not at my home computer
